/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_myapplication_jniTest_JniDemo */

#ifndef _Included_com_example_myapplication_jniTest_JniDemo
#define _Included_com_example_myapplication_jniTest_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_myapplication_jniTest_JniDemo
 * Method:    print
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myapplication_jniTest_JniDemo_print
  (JNIEnv *, jobject);

/*
 * Class:     com_example_myapplication_jniTest_JniDemo
 * Method:    getSomething
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_myapplication_jniTest_JniDemo_getSomething
  (JNIEnv *, jobject);

/*
 * Class:     com_example_myapplication_jniTest_JniDemo
 * Method:    testHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_myapplication_jniTest_JniDemo_testHello
  (JNIEnv *, jobject){
    printf("c++ hello world ")
  };

#ifdef __cplusplus
}
#endif
#endif
